Specify files on vim command-line when possible
If the vim instance needs to be started, specify the files on its
command-line.

When autosplit is enabled, this means we get a different file in each
pane, rather than them all in the first one.

If the vim instance is already running, send the files across as usual.

diff --git a/tmux-vim b/tmux-vim
--- a/tmux-vim
+++ b/tmux-vim
@@ -168,13 +168,13 @@ _vim_op() {
     _vim_send_keys :$1 space "${2// /\\ }" enter
 }
 
-# _vim_start
-# - split a new tmux pane and start vim in it
-# - the pane id is stored as tmux_vim_pane
+# _vim_start <files>
+# - spawns a new vim instance if necessary
+# - returns 1 if vim is already running, 0 if a new instance was started
 _vim_start() {
     if _tmux_is_running; then
         # tmux_vim already exists - try to select that pane
-        tmux select-pane -t $( _vim_pane_id ) && return
+        tmux select-pane -t $( _vim_pane_id ) && return 1
 
         # If we get here, that pane no longer exists, so fall thru
         # (shouldn't happen)
@@ -291,9 +291,15 @@ _vim_start() {
 
     local vim_bin=${TMUX_VIM_VIM_BIN:-vim}
 
+    if [[ $# -gt 0 ]]; then
+        # Add any files to the vim command-line. When autosplit is enabled,
+        # this means we get a different file in each pane.
+        local vim_files=$( printf '%q ' "$@" )
+    fi
+
     # Split a new pane, start vim in it, and record the pane index
     local tmux_vim_pane=$(tmux split-window -P -$split_method -l $split_size \
-                        "exec $vim_bin $vim_args")
+                        "exec $vim_bin $vim_args $vim_files")
 
     # Now convert the pane index into a global persistent id
     # 0:1.1: [100x88] [history 0/10000, 0 bytes] %2
@@ -303,6 +309,8 @@ _vim_start() {
 
     # Swap the panes if necessary. tmux only does right/bottom
     [[ $do_swap == 1 ]] && tmux swap-pane -D
+
+    return 0
 }
 
 # tmux_vim [files...]
@@ -313,33 +321,37 @@ tmux_vim() {
     [[ -f "$rcfile" ]] && source "$rcfile"
 
     _pre_flight_checks || exit 1
-    _vim_start
-    _vim_send_keys escape  # make sure we're in command mode
+    if ! _vim_start "$@"; then
 
-    if [[ $# -gt 0 ]]; then
+        # vim was already running, send the new files
+        if [[ $# -gt 0 ]]; then
 
-        # If we are now in a different directory than $TDIR, we want to make
-        # vim switch to this directory temporarily before opening the files.
-        # This obviates any relative path computations.
-        [[ "$PWD" != "$( _vim_last_dir )" ]] && _vim_op cd "$PWD"
+            _vim_send_keys escape  # make sure we're in command mode
 
-        # Rather than :edit each file in turn, use :badd for all but the last
-        # file, and then use :edit on that.
-        # This is to handle the situation where the current buffer is unsaved,
-        # and an :edit command will cause vim to prompt the user to save,
-        # abandon or cancel.
-        # If we just :edit each file, things just don't work out naturally;
-        # cancel works, but yes/no end up with only the first file opened.
-        # Errant escape keys cause the whole open to just silently fail.
-        # This approach pushes the user interaction right to the end.
-        while [[ $# -gt 1 ]]; do
-            _vim_op badd "$1"
-            shift
-        done
+            # If we are now in a different directory than $TDIR, we want to make
+            # vim switch to this directory temporarily before opening the files.
+            # This obviates any relative path computations.
+            [[ "$PWD" != "$( _vim_last_dir )" ]] && _vim_op cd "$PWD"
 
-        _vim_op edit "$1"
+            # Rather than :edit each file in turn, use :badd for all but the last
+            # file, and then use :edit on that.
+            # This is to handle the situation where the current buffer is unsaved,
+            # and an :edit command will cause vim to prompt the user to save,
+            # abandon or cancel.
+            # If we just :edit each file, things just don't work out naturally;
+            # cancel works, but yes/no end up with only the first file opened.
+            # Errant escape keys cause the whole open to just silently fail.
+            # This approach pushes the user interaction right to the end.
+            while [[ $# -gt 1 ]]; do
+                _vim_op badd "$1"
+                shift
+            done
 
-        [[ "$PWD" != "$( _vim_last_dir )" ]] && _vim_op cd -
+            _vim_op edit "$1"
+
+            [[ "$PWD" != "$( _vim_last_dir )" ]] && _vim_op cd -
+        fi
+
     fi
 
     tmux select-pane -t $( _vim_pane_id )
